### ISSUE TITLE
template axiom annotations do not work for class assertions on individuals

### ISSUE THREAD

**Issue by Clare72** [ontodev/robot#1156] opened 2023-10-11 14:14 UTC
\>A columns to the right of TI columns do not add anything to the output ontology (there is also no error message - just silent failure to add annotation)
using the same template but changing to classes (so SC column for axiom to be annotated) works fine

**Comment by Clare72** [comment] 2023-10-11 14:21
[neurotransmitter_predictions_template.txt](https://github.com/ontodev/robot/files/12870989/neurotransmitter_predictions_template.txt)

sorry - had to rename to txt to upload - should be tsv

run using ```robot template --template neurotransmitter_predictions_template.tsv --prefix "custom: http://n2o.neo/custom/" --output nt_predictions.owl```

**Comment by Clare72** [comment] 2023-10-11 14:23
It makes all the individuals and class assertions, but no annotations on the class assertions
If I change the type of the three individuals to owl:Class and TI to SC, then axiom annotations are added correctly

**Comment by jamesaoverton** [comment] 2023-11-29 13:59
This problem has the same root cause as #1133, and should be fixed by #1104.

**Closed by jamesaoverton** 2023-11-29 13:59 UTC
