### ISSUE TITLE
support for slims

### ISSUE THREAD

**Issue by simonjupp** [ontodev/robot#263] opened 2018-03-02 13:20 UTC
Has there been any discussion about how you might use ROBOT to extract a slim? I'd like something like 

`robot subset -t terms.txt` where the terms.txt file contains a list of IRIs for terms in the slim. I wouldn't want this tied to the OBO subset pattern as you could easily do a query operation first to generate the terms file from some APs in the ontology.

**Comment by rctauber** [comment] 2018-04-11 03:33
We are working on `remove` and `filter` commands - check out #272. I think `filter` will do exactly what you need.

**Comment by simonjupp** [comment] 2018-04-11 09:27
I'm not sure filter is enough to extract a slim. The owl-tools --extract-ontology-subset will fill in subclassOf axioms between terms in the slim which is a crucial part of the slimming process. 

So if I have a simple ontology with a hierarchy like
```
A
  - B
      - C
```
If A and C are in a subset and I try and extract it I should get a new ontology with 
```
A
  - C
```

It's not clear if the `filter` command would implement this.

**Comment by jamesaoverton** [comment] 2018-04-11 12:10
@simonjupp You're right that the current `filter` proposal doesn't cover that. We'll figure something out.

**Comment by simonjupp** [comment] 2018-08-07 21:17
I think this issue duplicates #302 and #254

**Comment by rctauber** [comment] 2018-08-13 15:42
I think the best way to handle this is through `filter`. I made some updates on a new branch: https://github.com/rctauber/robot/tree/gaps

This includes a new `--preserve-structure <true/false>` option. By default, this is true. Gaps are automatically spanned to maintain the structure in both `remove` and `filter`. If you don't want to maintain that structure, you can include `--preserve-structure false`.

So, going off your above example, if your input term set includes classes `A` and `C`, you will get:
```
owl:Thing
  - A
    - C
```

But with `--preserve-structure false`, you would get:
```
owl:Thing
  - A
  - C
```

Filling in the entire hierarchy (fill gaps, instead of span gaps) can be achieved with a two-step filter:
```
robot filter --input foo.owl \
  --term-file subset_terms.txt \
  --select "self ancestors annotations" \
filter --term-file subset_terms.txt \
  --select "self descendants annotations" \
  --output bar.owl
```

@simonjupp - I would appreciate if you could test this out and let me know if it works for your use case!

**Comment by cmungall** [comment] 2018-08-14 00:54
does spanning only cover named classes?

E.g. if I wanted to make a slim with just {nucleus, cell} from

 * nucleus subClassOf 'cell part'
 * 'cell part' subClassOf part_of some cell

Would there be a gap?

There are a variety of approaches to doing this. To be guaranteed complete reasoning would have to be used. The EMR could be used

**Comment by jamesaoverton** [comment] 2018-08-14 13:06
The current implementation relies on `EntitySearcher.getSuperClasses` which returns `OWLClassExpression`s, so I think it includes anonymous classes. Is this always what's wanted?

We have `remove --select anonymous` that can get rid of anonymous stuff in a second step.

Honestly, I don't have a precise understanding of what people mean by "slim".

**Comment by rctauber** [comment] 2018-08-14 14:08
I just changed it so that if all the parts of the expression are in the filtered objects, then the anonymous superclass will be included (so `part_of` would have to be in the set).

It won't traverse the anonymous expressions, though, unless you used EMR first. The expression would have to be a direct superclass to one of the filtered terms, and include only terms from the filtered terms.

**Comment by cmungall** [comment] 2018-08-14 20:01
> It won't traverse the anonymous expressions, though, unless you used EMR first. The expression would have to be a direct superclass to one of the filtered terms, and include only terms from the filtered terms

OK - so it would work for my example, but not for `A isa B partof C partof D` where subset={A,D}.

Happy to have this done on a future iteration with a new ticket made for this as a feature enhancement

> Honestly, I don't have a precise understanding of what people mean by "slim".

I propose as a formal definition: a class subset that is entailment-preserving

**Comment by rctauber** [comment] 2018-08-15 15:33
I'll make a PR for my branch to resolve this issue, then perhaps we can continue the discussion for your example on #302?

**Comment by matentzn** [comment] 2018-08-28 07:26
> I propose as a formal definition: a class subset that is entailment-preserving

I feel we should be a bit careful with defining slim in that way.. I doubt it would withhold any formal proof of entailment-preserving. Perhaps subsumption preserving, but even that, I am not so sure.

I agree though a more clear definition would be good. In general terms, is a slim supposed to be a subset of the class hierarchy (i.e. containing only SubClassOf axioms between named classes)? Do you use a reasoner when extracting a slim?

**Comment by cmungall** [comment] 2018-08-28 15:33
Subclass entailment preserving?

**Comment by cmungall** [comment] 2018-08-28 15:35
We should use reasoning. Owltools did basic graph walking and chaining

**Comment by rctauber** [comment] 2018-08-28 15:57
We could add a `--reasoner` option to `filter` and `remove`. The reasoner would run before any of the filter/remove operations.

**Comment by rctauber** [comment] 2019-01-30 16:35
We currently have the `--preserve-structure` option in remove and filter which I believe meets the requirements that @simonjupp requested. @cmungall do we want to open a new issue to discuss including reasoning in this?

**Comment by cmungall** [comment] 2019-02-02 21:39
Sorry haven't had time to test.

Don't want to block this but I think there is a certain set of expected behaviors that people want from slimming and it would be good to have this be the default from the start

**Comment by cmungall** [comment] 2019-06-06 22:58
I'm going to close this now as I specified more precisely the features required for subsetting here: #497

**Closed by cmungall** 2019-06-06 22:58 UTC
Labels: enhancement
