### ISSUE TITLE
Any clue what is wrong when you get a Error 1?

### ISSUE THREAD

**Issue by rduerr** [ontodev/robot#981] opened 2022-03-29 01:48 UTC
I am receiving a Error 1 when I run prepare_release (both locally and on github).  The command that is failing seems to be 
`robot --catalog catalog-v001.xml convert --input sddo.owl --check false -f obo  -o sddo.obo.tmp.obo && grep -v ^owl-axioms sddo.obo.tmp.obo > sddo.obo && rm sddo.obo.tmp.obo`

so I added -vvv to it and the output ends in:

`2022-03-28 19:18:08,878 DEBUG org.semanticweb.owlapi.rdf.rdfxml.parser.OptimisedListTranslator - list: <http://purl.obolibrary.org/obo/UBERON_0000477>
2022-03-28 19:18:08,879 DEBUG org.semanticweb.owlapi.rdf.rdfxml.parser.OptimisedListTranslator - list: ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0000087> <http://purl.obolibrary.org/obo/OBI_0000112>)
2022-03-28 19:18:08,879 DEBUG org.semanticweb.owlapi.rdf.rdfxml.parser.OptimisedListTranslator - list: <http://purl.obolibrary.org/obo/UBERON_0000465>
2022-03-28 19:18:08,879 DEBUG org.semanticweb.owlapi.rdf.rdfxml.parser.OptimisedListTranslator - list: <http://purl.obolibrary.org/obo/UBERON_0000477>
2022-03-28 19:18:08,879 DEBUG org.semanticweb.owlapi.rdf.rdfxml.parser.OptimisedListTranslator - list: ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0001000> ObjectUnionOf(<http://purl.obolibrary.org/obo/UBERON_0000465> <http://purl.obolibrary.org/obo/UBERON_0000477>))
2022-03-28 19:18:08,893 DEBUG org.semanticweb.owlapi.rdf.rdfxml.parser.TripleLogger - Loaded OntologyID(OntologyIRI(<http://purl.obolibrary.org/obo/sddo.owl>) VersionIRI(<http://purl.obolibrary.org/obo/sddo/releases/2022-03-29/sddo.owl>))
2022-03-28 19:18:08,996 DEBUG org.obolibrary.robot.IOHelper - Saving ontology Ontology(OntologyID(OntologyIRI(<http://purl.obolibrary.org/obo/sddo.owl>) VersionIRI(<http://purl.obolibrary.org/obo/sddo/releases/2022-03-29/sddo.owl>))) [Axioms: 5330 Logical Axioms: 910] First 20 axioms: {SubDataPropertyOf(<http://purl.obolibrary.org/obo/SDDO_5000004> <http://purl.obolibrary.org/obo/SDDO_5000003>) SubDataPropertyOf(<http://purl.obolibrary.org/obo/SDDO_5000003> <http://purl.obolibrary.org/obo/SDDO_5000002>) SubDataPropertyOf(<http://purl.obolibrary.org/obo/SDDO_5000002> <http://purl.obolibrary.org/obo/SDDO_5000001>) SubDataPropertyOf(<http://purl.obolibrary.org/obo/SDDO_5000005> <http://purl.obolibrary.org/obo/SDDO_5000004>) SubClassOf(<http://purl.obolibrary.org/obo/UO_0000280> <http://purl.obolibrary.org/obo/IAO_0000003>) SubClassOf(<http://purl.obolibrary.org/obo/SDDO_/SDDO_1000000> <http://purl.obolibrary.org/obo/SDDO_3000048>) SubClassOf(<http://purl.obolibrary.org/obo/SDDO_3000092> <http://purl.obolibrary.org/obo/SDDO_3000054>) SubClassOf(<http://purl.obolibrary.org/obo/SDDO_3000112> <http://purl.obolibrary.org/obo/SDDO_3000088>) SubClassOf(<http://purl.obolibrary.org/obo/OBI_0200000> <http://purl.obolibrary.org/obo/OBI_0000011>) SubClassOf(<http://purl.obolibrary.org/obo/SDDO_3000094> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/SDDO_3000042> <http://purl.obolibrary.org/obo/SDDO_3000088>)) SubClassOf(<http://purl.obolibrary.org/obo/UO_0000095> <http://purl.obolibrary.org/obo/IAO_0000003>) SubClassOf(<http://purl.obolibrary.org/obo/SDDO_3000102> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/SDDO_3000033> <http://purl.obolibrary.org/obo/SDDO_3000074>)) SubClassOf(<http://purl.obolibrary.org/obo/SDDO_3000044> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/SDDO_3000041> <http://purl.obolibrary.org/obo/SDDO_3000100>)) SubClassOf(<http://purl.obolibrary.org/obo/SDDO_/SDDO_1000004> <http://purl.obolibrary.org/obo/SDDO_3000048>) SubClassOf(<http://purl.obolibrary.org/obo/OBI_0001930> <http://purl.obolibrary.org/obo/OBI_0001933>) SubClassOf(<http://purl.obolibrary.org/obo/NCBITaxon_2759> <http://purl.obolibrary.org/obo/OBI_0100026>) SubClassOf(<http://purl.obolibrary.org/obo/IAO_0000308> <http://purl.obolibrary.org/obo/IAO_0000030>) SubClassOf(<http://purl.obolibrary.org/obo/OBI_0000094> ObjectAllValuesFrom(<http://purl.obolibrary.org/obo/OBI_0000293> <http://purl.obolibrary.org/obo/BFO_0000040>)) SubClassOf(<http://purl.obolibrary.org/obo/SDDO_3000102> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/SDDO_3000019> <http://purl.obolibrary.org/obo/SDDO_3000075>)) SubClassOf(<http://purl.obolibrary.org/obo/SDDO_3000051> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/OBI_0000312> ObjectUnionOf(<http://purl.obolibrary.org/obo/SDDO_3000088> <http://purl.obolibrary.org/obo/SDDO_3000094>))) } as OBO Format with to IRI file:/Users/ruthduerr/src/sddo/src/ontology/sddo.obo.tmp.obo
2022-03-28 19:18:09,333 DEBUG org.obolibrary.robot.ExceptionHelper - {} missing exception message.
java.lang.NullPointerException
	at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:619)
	at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:351)
	at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:197)
	at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:171)
	at org.obolibrary.robot.IOHelper.saveOntologyFile(IOHelper.java:1164)
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:610)
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:551)
	at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:167)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:248)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:192)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:56)
null
java.lang.NullPointerException
	at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:619)
	at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:351)
	at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:197)
	at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:171)
	at org.obolibrary.robot.IOHelper.saveOntologyFile(IOHelper.java:1164)
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:610)
	at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:551)
	at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:167)
	at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:248)
	at org.obolibrary.robot.CommandManager.execute(CommandManager.java:192)
	at org.obolibrary.robot.CommandManager.main(CommandManager.java:139)
	at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:56)
`
Which seems to indicate some sort of write error; but this particular error seems to have a missing exception message.  Help!!!

I do note that the file it is writing to ( IRI file:/Users/ruthduerr/src/sddo/src/ontology/sddo.obo.tmp.obo) does seem to be truncated but it isn't obvious what the next lines should be or why the file isn't complete....

Just in case it is helpful, here is a tail of both files...
`(base) Ruths-iMac:ontology ruthduerr$ tail -40 sddo.owl
    //
    ///////////////////////////////////////////////////////////////////////////////////////
     -->

    <rdf:Description>
        <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#AllDisjointClasses"/>
        <owl:members rdf:parseType="Collection">
            <rdf:Description rdf:about="http://purl.obolibrary.org/obo/BFO_0000004"/>
            <rdf:Description rdf:about="http://purl.obolibrary.org/obo/BFO_0000020"/>
            <rdf:Description rdf:about="http://purl.obolibrary.org/obo/BFO_0000031"/>
        </owl:members>
    </rdf:Description>
    <rdf:Description>
        <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#AllDifferent"/>
        <owl:distinctMembers rdf:parseType="Collection">
            <rdf:Description rdf:about="http://purl.obolibrary.org/obo/IAO_0000120"/>
            <rdf:Description rdf:about="http://purl.obolibrary.org/obo/IAO_0000121"/>
            <rdf:Description rdf:about="http://purl.obolibrary.org/obo/IAO_0000122"/>
            <rdf:Description rdf:about="http://purl.obolibrary.org/obo/IAO_0000123"/>
            <rdf:Description rdf:about="http://purl.obolibrary.org/obo/IAO_0000124"/>
            <rdf:Description rdf:about="http://purl.obolibrary.org/obo/IAO_0000125"/>
            <rdf:Description rdf:about="http://purl.obolibrary.org/obo/IAO_0000423"/>
            <rdf:Description rdf:about="http://purl.obolibrary.org/obo/IAO_0000428"/>
        </owl:distinctMembers>
    </rdf:Description>
    <rdf:Description>
        <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#AllDifferent"/>
        <owl:distinctMembers rdf:parseType="Collection">
            <rdf:Description rdf:about="http://purl.obolibrary.org/obo/IAO_0000226"/>
            <rdf:Description rdf:about="http://purl.obolibrary.org/obo/IAO_0000227"/>
            <rdf:Description rdf:about="http://purl.obolibrary.org/obo/IAO_0000228"/>
            <rdf:Description rdf:about="http://purl.obolibrary.org/obo/IAO_0000229"/>
        </owl:distinctMembers>
    </rdf:Description>
</rdf:RDF>

(base) Ruths-iMac:ontology ruthduerr$ tail -40 sddo.obo.tmp.obo 
id: SDDO:3000112
name: researchMission
def: "A mission that gather scientific data" []
is_a: SDDO:3000088 ! mission

[Term]
id: SDDO:3000113
name: firmware
def: "Software that provides the low-level control for a device's specific hardware." []
is_a: IAO:0000010 ! software
relationship: BFO:0000050 SDDO:3000054 ! part of hardware
property_value: IAO:0000117 https://orcid.org/0000-0003-4808-4736
property_value: IAO:0000119 https://en.wikipedia.org/wiki/Firmware

[Term]
id: SDDO:3000114
name: observableDiscoveryCriterion
is_a: SDDO:3000074 ! dataDiscoveryCriterion

[Term]
id: SDDO:3000115
name: platformDiscoveryCriterion
is_a: SDDO:3000074 ! dataDiscoveryCriterion

[Term]
id: SWO:0000001
name: software
def: "Computer software, or generally just software, is any set of machine-readable instructions (most often in the form of a computer program) that conform to a given syntax (sometimes referred to as a language) that is interpretable by a given processor and that directs a computer's processor to perform specific operations." []
is_a: IAO:0000030 ! information content entity
relationship: SWO:0040005 OBI:0200000 ! is executed in data transformation
property_value: IAO:0000119 "James Malone" xsd:string
property_value: IAO:0000119 "Modified in parts from https://en.wikipedia.org/wiki/Software" xsd:string
property_value: IAO:0000119 "Robert Stevens" xsd:string

[Term]
id: SWO:0000002
name: licence
name: software license
def: "A licence is a legal instrument (usually by way of contract law, with or without printed material) governing the use or redistribution of the resource containing the licence." []
is_a: IAO:0000030 ! information content entity
(`

**Comment by jamesaoverton** [comment] 2022-03-29 14:23
Sorry for the missing error message. This does look like an OBO-format writer problem to me, which is part of the OWLAPI codebase. Can any of our OBO-format experts help?

**Comment by matentzn** [comment] 2022-03-31 12:32
Hey @rduerr - This is very hard to say from here. As @jamesaoverton hints at, your error is likely caused by an incompatibility between your OWL ontology and the OBO format - this can be very daunting to review so if you send me your input file, I will try to figure this out for you..

**Comment by rduerr** [comment] 2022-03-31 19:36
Hi @matentzn the file is at https://raw.githubusercontent.com/NASA-IMPACT/sddo/17-complete-definitions-for-all-sddo-terms/src/ontology/sddo-edit.owl.  The problem is caused by the import of terms from the SWO ontology.  Without that import things are fine, with it - well we get an error...  It's a public repo so, have at it.  I also note that I've found out through the grapevine that other ODK based repositories have had similar problems and have been simply commenting the .obo lines out of the Makefile (as has been done here and not according to the ODK instructions either).  I'm not sure what you all ought to do about that... There seems to be some hesitancy in the community to write issues or get help....

**Comment by matentzn** [comment] 2022-04-01 07:27
@rduerr I have updated your repo to latest ODK and sorted your import issues, see: https://github.com/NASA-IMPACT/sddo/pull/24

I am happy to meet you to train you and Dan and anyone else who is interested to properly manage your ODK repo moving forward!

Note that your main problem was to import SWO using some EBI URL - you should always use the proper ODK import system for cases like this. 

I will close this issue here, but feel free to open new issues here moving forward:
https://github.com/INCATools/ontology-development-kit

Also, send me an email if you want an invite to our slack, so I can help you much quicker.

**Closed** 2022-04-01 07:27 UTC

**Comment by matentzn** [comment] 2022-04-01 07:29
I forgot to say: "Fixing" this caused quite a few sddo classes to become unsatisfiable.. You can check out my branch, open sddo-edit.owl and run the reasoner and see:

<img width="632" alt="image" src="https://user-images.githubusercontent.com/7070631/161216183-c7459af7-9918-41a6-b33c-955a2e267cbd.png">

**Comment by matentzn** [comment] 2022-04-01 07:35
There are, at least, some incompatibilities between OBI and SWO:

```
robot merge -I http://purl.obolibrary.org/obo/obi.owl -I http://purl.obolibrary.org/obo/swo.owl reason

ERROR The ontology is inconsistent. TIP: use a tool like Protege to find explanations
```

**Comment by rduerr** [comment] 2022-04-01 23:04
@matentzn Both Dan Berrios and I will gratefully take you up on the offer of ODK training!  How do you want to set up a time?

**Comment by DanBerrios** [comment] 2022-04-23 00:10
@matentzn  I was able to trace what the incompatible items in SWO were and custom-remove them from our import.  So we have a workaround...thanks, Nico!
